syntax enable
filetype plugin on

set path+=**
set wildmenu
set laststatus=2
set mouse=nv
set incsearch
set hlsearch
set ignorecase smartcase
set autoindent
set smartindent
set smarttab
set indentexpr=
set expandtab shiftwidth=4 tabstop=4

cmap w!! w !sudo tee > /dev/null %

silent !mkdir -p ~/.cache/vim/{swap,backup,undo}
silent !find ~/.cache/vim/undo -type f -mtime +30 -delete
set viminfo+=n~/.cache/vim/info
set backup backupdir=~/.cache/vim/backup//
set swapfile directory=~/.cache/vim/swap//
set undofile undodir=~/.cache/vim/undo//
